AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  # Note that this name is used in the Makefile
  RootDomainName:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
Mappings:
  Region2S3WebsiteSuffix:
    us-east-1:
      Suffix: .s3-website-us-east-1.amazonaws.com
    eu-west-1:
      Suffix: .s3-website-eu-west-1.amazonaws.com
Resources:
  S3BucketForWebsiteContent:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref 'RootDomainName'
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  TLSCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref RootDomainName
      SubjectAlternativeNames:
        - !Join ['.', ['www', !Ref 'RootDomainName']]
  WebsiteCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref 'RootDomainName'
        - !Join ['.', ['www', !Ref 'RootDomainName']]
        Comment: !Join [' ', ['CDN for', !Ref 'RootDomainName']]
        Enabled: true
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: !Ref TLSCertificate
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          MaxTTL: 3600
          ForwardedValues:
            QueryString: false
          TargetOriginId: s3-bucket-website
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Origins:
        - Id: s3-bucket-website
          DomainName: !Join ['', [!Ref 'S3BucketForWebsiteContent', 
                !FindInMap [Region2S3WebsiteSuffix, !Ref 'AWS::Region', Suffix]]]
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
  WebsiteDNSName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join ['', [!Ref 'RootDomainName', .]]
      Comment: !Join [' ', ['Alias from', !Ref 'RootDomainName', 'to the CDN and a CNAME record for WWW']]
      RecordSets:
      - Name: !Ref 'RootDomainName'
        Type: A
        AliasTarget:
          DNSName: !GetAtt [WebsiteCDN, DomainName]
          # For CloudFront, use Z2FDTNDATAQYW2, see http://docs.aws.amazon.com/general/latest/gr/rande.html
          HostedZoneId: Z2FDTNDATAQYW2
      - Name: !Join ['.', ['www', !Ref 'RootDomainName']]
        Type: CNAME
        TTL: 600
        ResourceRecords:
        - !Ref 'RootDomainName'
Outputs:
  BucketName:
    Value: !Join ['', ['s3://', !Ref 'S3BucketForWebsiteContent']]
    Description: The URI of the S3 bucket that holds the website content
  BucketWebsiteURL:
    Value: !GetAtt [S3BucketForWebsiteContent, WebsiteURL]
    Description: The URL of the S3 bucket website
  # Note that this name is used in the Makefile  
  CloudFrontDistributionId:
    Value: !Ref WebsiteCDN  
    Description: The CloudFront Distribution Id to be used for creating invalidations during deployment
  WebsiteURL:
    Value: !Join ['', ['https://', 'www.', !Ref RootDomainName]]
    Description: The URL of the newly created website
