AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  HostedZone:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
Resources:
  S3BucketForWebsiteContent:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref 'HostedZone'
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  WebsiteCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref 'HostedZone'
        Comment: !Join [' ', ['CDN for', !Ref 'HostedZone']]
        Enabled: 'true'
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: 'true'
          TargetOriginId: only-origin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Origins:
        - CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
          DomainName: !GetAtt [S3BucketForWebsiteContent, DomainName]
          Id: only-origin
  WebsiteDNSName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join ['', [!Ref 'HostedZone', .]]
      Comment: !Join [' ', ['Alias from', !Ref 'HostedZone', 'to the CDN and a CNAME record for WWW']]
      RecordSets:
      - Name: !Ref 'HostedZone'
        Type: A
        AliasTarget:
          DNSName: !GetAtt [WebsiteCDN, DomainName]
          # For CloudFront, use Z2FDTNDATAQYW2, see http://docs.aws.amazon.com/general/latest/gr/rande.html
          HostedZoneId: Z2FDTNDATAQYW2
      - Name: !Join ['.', ['www', !Ref 'HostedZone']]
        Type: CNAME
        TTL: 600
        ResourceRecords:
        - !Ref 'HostedZone'
Outputs:
  WebsiteRootURL:
    Value: !Join ['', ['http://', !Ref 'WebsiteDNSName']]
    Description: The URLs of the newly created website
  BucketName:
    Value: !Ref 'S3BucketForWebsiteContent'
    Description: Name of S3 bucket to hold website content